<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE People[
        <!ELEMENT People (Person+)>
        <!ELEMENT Person (Name,Address,Sex)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Sex (#PCDATA)>
        <!ATTLIST Person
                id CDATA #REQUIRED>
        ]>
<People>
    <Person id="1">
        <Name> chao j un </Name>
        <Address>Shanghai</Address>
        <Sex>male</Sex>
    </Person>
    <Person id="2">
        <Name>qin cha o</Name>
        <Address>Shanxi</Address>
        <Sex>female</Sex>
    </Person>
</People>
